{
 "title": "Parser banks",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   { "name": "bank", "label": "bank", "query": "select bank_name from bank" },
   { "name": "source_type_val", "label": "source_type", "query": "select name from source_type" },
   { "name": "model_val", "label": "model", "query": "select name from model" }
  ]
 },
 "panels": [
  {
   "title": "Количество отзывов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(id) AS \"sravni\"\nFROM text\nWHERE\n  $__timeFilter(date) AND\n  source_id = (SELECT id from source where site = 'sravni.ru')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(id) AS \"banki\"\nFROM text\nWHERE\n  $__timeFilter(date) AND\n  source_id = (SELECT id from source where site = 'banki.ru')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "text_result",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  model.name,\n  count(text_result.id) AS \"text_result\"\nFROM text_result\njoin\n  model on text_result.model_id = model.id\ngroup by model.name"
    }
   ]
  },
  {
   "title": "text_sentence",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  source.site,\n  count(text_sentence.id) AS \"text_sentence\"\nFROM text_sentence\njoin \n  text on text.id = text_sentence.text_id\njoin\n  source on text.source_id = source.id\ngroup by source.site"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM source\nORDER BY 1"
    }
   ]
  },
  { "title": "Per bank", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Отзывы на банк",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(bank_id) AS \"sravni_ru\"\nFROM text\nWHERE\n  $__timeFilter(date) \n  AND text.bank_id = (SELECT id from bank where bank_name = '${bank}')\n  AND text.source_id = (SELECT id from source where site = 'sravni.ru')\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(bank_id) AS \"banki_ru\"\nFROM text\nWHERE\n  $__timeFilter(date) \n  AND text.bank_id = (SELECT id from bank where bank_name = '${bank}')\n  AND text.source_id = (SELECT id from source where site = 'banki.ru' )\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Отзывы на банк",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(result[1]) as neutral,\n  date_trunc('year', text.date) as time\nFROM\n  text_result\n  left JOIN text_sentence on text_result.text_sentence_id=text_sentence.id\n  left JOIN text on text_sentence.text_id = text.id\nwhere\n  text_result.model_id = (SELECT id from model where name = '${model_val}')\n  and text.bank_id = (SELECT id from bank where bank_name = '${bank}')\nGROUP BY\n  time"
    },
    {
     "rawSql": "SELECT\n  avg(result[2]) as positive,\n  date_trunc('year', text.date) as time\nFROM\n  text_result\n  left JOIN text_sentence on text_result.text_sentence_id=text_sentence.id\n  left JOIN text on text_sentence.text_id = text.id\nwhere\n  text_result.model_id = (SELECT id from model where name = '${model_val}')\n  and text.bank_id = (SELECT id from bank where bank_name = '${bank}')\nGROUP BY\n  time"
    },
    {
     "rawSql": "SELECT\n  avg(result[3]) as negative,\n  date_trunc('year', text.date) as time\nFROM\n  text_result\n  left JOIN text_sentence on text_result.text_sentence_id=text_sentence.id\n  left JOIN text on text_sentence.text_id = text.id\nwhere\n  text_result.model_id = (SELECT id from model where name = '${model_val}')\n  and text.bank_id = (SELECT id from bank where bank_name = '${bank}')\nGROUP BY\n  time"
    }
   ]
  }
 ]
}