#+STARTUP: latexpreview
#+TITLE: Разработка сайта для автоматического сбора, анализа и визуализации информации по этичности компаний
#+AUTHOR: Соломатин Роман Игоревич
#+LANGUAGE: RU
#+LATEX_CLASS: HSEUniversity
#+LATEX_CLASS_OPTIONS: [PI, VKR]
#+bibliography: library.bib
#+cite_export: biblatex
#+OPTIONS: toc:nil H:4 ':t
#+LATEX_HEADER_EXTRA: \Abstract{В данной работе проведен анализ этичности разных компаний.
#+LATEX_HEADER_EXTRA:
#+LATEX_HEADER_EXTRA: В первой главе находится описание используемых алгоримов.
#+LATEX_HEADER_EXTRA:
#+LATEX_HEADER_EXTRA: Во второй главе представлено проектирование системы.
#+LATEX_HEADER_EXTRA:
#+LATEX_HEADER_EXTRA: В третьей главе представлена реализация системы.
#+LATEX_HEADER_EXTRA:
#+LATEX_HEADER_EXTRA: В четвертой главе представлено тестирование работы системы.
#+LATEX_HEADER_EXTRA:
#+LATEX_HEADER_EXTRA: Количество страниц - N, количество иллюстраций - N, количетсво таблиц - N.}

* Введение
:PROPERTIES:
:UNNUMBERED: t
:END:
Этичность компаний уже давно вызывает озабоченность, особенно в отношении их поведения в спорных ситуациях и предоставления услуг, ориентированных на клиента. В последние годы все большее внимание уделяется оценке этичности компаний[cite:@mure_esg_2021], особенно в банковском секторе и через призму экологических, социальных и управленческих факторов (ESG). Необходимость в таких оценках становится все более острой по мере того, как общество продолжает бороться с последствиями неправомерных действий корпораций и более широким воздействием корпоративной деятельности на общество и окружающую среду.

В настоящее время существует несколько сервисов, которые призваны оценивать этику компании, но эти оценки часто основаны на судебных делах и других официальных отчетах, а не на отзывах клиентов. Это привело к ситуации, когда отдельные лица должны проводить свои собственные исследования, чтобы определить насколько этична компания. Это часто включает в себя просмотр отзывов с различных веб-сайтов, что может занять много времени и не всегда может дать исчерпывающую или точную картину.

Для решения этой проблемы будет реализована система, которая собирала бы и анализировала отзывы потребителей с различных веб-сайтов, чтобы дать более полную и точную оценку этической практики компании. Такая система может быть разработана для автоматического сбора и анализа отзывов потребителей из различных источников, включая социальные сети и сайты отзывов. Затем собранные данные могут быть проанализированы с помощью различных методов, таких как обработка естественного языка и машинное обучение, для выявления закономерностей и тенденций, связанных с этической практикой компании. Полученный анализ может быть использован для разработки более надежной и достоверной системы оценки этичности компаний.

Объект исследования – деятельность компаний.

Предмет исследования – программные средства для оценки этичности деятельности компаний.

Цель работы – создание системы для оценки этичности компаний.

Исходя из поставленной цели, необходимо:

1. Провести анализ предметной области
2. Провести анализ системы
3. Реализовать систему
4. Провести тестирование системы

Этап анализа должен:
1. Анализ предметной области
2. Анализ существующих алгоритмов

Этап проектирования должен включать:
1. Проектирование серверной части
2. Проектирование модели для определения этичности
3. Проектирование клиентской части приложения

Этап реализации должен включать:
1. Описание сбора данных
2. Реализации модели
3. Реализации серверной части
4. Реализации клиентской части

Этап тестирования должен включать:
1. Тестирование модели
2. Тестирование серверной части
3. Тестирование клиентской части
* Анализ предметной области
** Способы оценки этичности компаний
Компаниям важно оставаться этичными, так как на долгосрочной перспективе это приносит большую прибыль и улучшает показатели бизнеса, чем неэтичный способ ведение бизнеса[cite:@climent_ethical_2018; @mure_esg_2021]. На сколько этична компания можно с двух сторон, самой компании и их клиентов. Со стороны компаний можно выделить факторы, которые можно получить из их отчетности:
- Количество капитала, чтобы они не могли обанкротиться
- какое влияние они вносят на окружающую среду
- куда идут инвестиции[cite:@harvey1995ethical]

Для пользователей одним из ключевых факторов можно выделить:
- качество пользовательского сервиса[cite:@brunk2010exploring]
- на сколько навязчивые услуги компании[cite:@mitchell1992bank]

Кроме того, важно отметить, что оценка этики компании - это не одноразовый процесс, а скорее непрерывная попытка понять и оценить действия, политику и практику компании с течением времени. Это включает в себя рассмотрение соблюдения компанией отраслевых этических стандартов и передовой практики, а также мониторинг любых изменений в этической позиции компании с течением времени. Кроме того, участие в диалоге с компанией и консультации с организациями, специализирующимися на оценке корпоративной ответственности, могут дать ценную информацию об этических практиках компании.

В этой работе для анализа текстов будут использоваться алгоритмы машинного обучения.
** Алгоритмы для анализа текста
Алгоритмы машинного обучения для анализа текста получили широкое распространение для извлечения информации из неструктурированных данных с помощью больших помеченных наборов данных. Среди различных используемых методов несколько алгоритмов оказались особенно эффективными в этой области. К ним относятся мешок слов[cite:@doi:10.1080/00437956.1954.11659520], TF-IDF[cite:@jones1972statistical], Word2Vec[cite:@mikolov2013distributed], ELMO[cite:@elmo], GPT[cite:@radford2019language] и BERT[cite:@devlin2018bert]. Каждый из этих алгоритмов обладает уникальными характеристиками, которые делают их хорошо подходящими для определенных приложений.

Модель "Мешок слов" представляет текстовые данные путем присвоения уникального номера каждому слову в документе. Этот метод прост в своей реализации, но не учитывает порядок слов в предложении. Модель TF-IDF, с другой стороны, представляет текстовые данные, учитывая как частоту слова в документе (TF), так и его важность в общем наборе данных (IDF). Это простые методы анализа текста и не учитывают контекст текста.

Word2Vec, ELMO, GPT и BERT - все это алгоритмы на основе нейронных сетей, которые представляют текстовые данные более сложным способом. Word2Vec представляет слова в виде векторов и может фиксировать значение слов в аналогичных контекстах. ELMO, GPT и BERT основаны на архитектуре transformer, где каждое предложение представлено вектором цифр (эмбеддингом). BERT -- лучше остальных алгоритмов понимает текст, так как он может рассматривать слова в контексте всего предложения или текста, когда GPT и ELMO рассматривают только односторонний контекст.

Также для объединения эмбеддинговых пространств будет работать алгоритм подобный CLIP[cite:@radford2021learning], только для трансформации текста в текст.
** Методы
* Проектирование системы
** Проектирование базы данных

** Проектирование архитектуры системы
*** Проектирование серверной части
*** Проектирование клиентской части

* Реализация системы
** Реализация серверной части
*** Реализация API
*** Реализация парсера banki.ru
*** Реализация парсера sravni.ru
*** Реализация модуля обработки текста
** Реализация клиентской части
* Тестирование системы
* Заключение
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: %\nocite{*}
#+LATEX: \putbibliography
#+LATEX: \appendix
